apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume

spec:
  containers:
    - name: mysql-volume
      image: mysql
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-volume
      env:
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_USER
          value: eazy
        - name: MYSQL_PASSWORD
          value: eazy
        - name: MYSQL_ROOT_PASSWORD
          value: password

  volumes:
    - name: data-volume
      hostPath:
        path: /data-volume
        type: Directory
